### ISSUE TITLE
[Feature request] Jekyll support

### ISSUE THREAD

**Issue by bkielbasa** [BoostIO/Boostnote#3117]
# Current behavior

It would be cool to have the possibility to use boostnote as the editor for Jekyll blogs.

**Comment by AWolf81** [comment]
@bkielbasa your request sounds interesting. Could you please add more details about how this feature should work? I haven't used Jekyll yet as I'm working with Gatsby at the moment.

Should it work like this?
1. Add the project folder of your static site as a location to Boostnote or select create new Jekyll site.
2. Boostnote will start the static site build script and display the page in the preview panel.
3. Boostnote will display all Markdown files in the editor section 
4. Hot-reloading will re-build the site with 500ms debouncing.
5. Creating new files will create new files in the project folder. (default as draft - configurable)
6. Use `_drafts` folder and `_posts` folder to filter the displayed posts in the editor. Changing from draft to published will move the file location to `_posts` 

**Some point we have to discuss / check:**
- How to add a new data file type? Boostnote is saving it's file as CSON files. Can this be refactored so it's easier to add markdown files?
- Should the build script that's executed be configurable? e.g. at Gatsby projects it's usually `yarn develop`. For Jekyll it's `bundle exec jekyll serve` that's calling bundler gem and jekyll gem.
- How should we install Jekyll on the system? Or should this be installed by the user? I think there should be a button that is triggering a setup cross-platform if the user likes to use Jekyll. https://jekyllrb.com/docs/installation/
- Add a check before displaying/installing the feature. Check if `Jekyll`, `Ruby` and `Bundler` are available. 
- Should this feature be opt-out by default as it requires additional setup?
- Should we also support other static site generators? E.g. Gatsby can be customized with a theme or starter to have a similar behaviour like Jekyll e.g. `_drafts` and `_posts` folder as data source is also possible.

**Comment by bkielbasa** [comment]
From my point of view, the functionality should be much more limited than you suggested. I don't want to make boostnote as an IDE :) 

## What would fully satisfy me would be

- possibility to choose a folder with pages (posts, drafts)
- full markdown support
- edit/add a new file from Boostnote

## Nice to have
- parsing and displaying tags/attributes
![image](https://user-images.githubusercontent.com/1235620/62050904-83172b80-b212-11e9-999c-974e61e08763.png)

```
---
layout: page
title: About
permalink: /about/
---
```
- correctly displaying images (the problem is that static files are in a different path comparing to the compiled source so very often they aren't visible due to an incorrect path)

## What I don't want
 - Building or running can be done from the command line
- edit themes or any other files which aren't markdown files

let's keep it simple :)

**Comment by AWolf81** [comment]
👍 Sounds better & easier. I'll have a look and check what I can do to add it.

**Todos to add the feature:**
- [ ] Add a Jekyll or Gatsby project folder as a storage location and display `_drafts` and `_post` folders (probably as filters). (New filesystem type for MD files required.) Later, add `_drafts` & `_posts` as an option to storage location preferences to support other project types - no editing menu for this available yet.
- [ ] Add directly editing of Markdown files instead of CSON files
- [ ] New note as markdown file in project folder - this requires a "storage location type" so we can check if it's a markdown storage or a standard Boostnote storage location (CSON).
- [ ] Check image loading in preview (maybe use localhost URL instead of a system path)
- [ ] [Nice-to-have] Preview of Jekyll/Gatsby dev server as Web view instead of the default Boostnote preview
- [ ] [Nice-to-have] Parse & Preview frontmatter tags/attributes

**Comment by spiritbro1** [comment]
is there any update on this one? is it already done or no?
