### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#68]
# Requested features

> To request a feature or improvement, please make a new issue! I'll add it to here after I checked.
# UI
## General
- [ ] Fully customizable theme
- [x] Add version info to Help menu #135
- [ ] Multiple screen switching(single / two / Three Panes)
## Menubar app(EVA) #58 #85
- [ ] Creating note #94
- [ ] Searching note
- [ ] Renew UI
  - [ ] Enhance search behaviour
  - [ ] Window position(Center of screen and Traybar)
- [ ] Wrong position when using multiple screens in Linux #88 #102
## Sidebar
- [x] Show context menu when right clicking folder item(rename, delete)
- [x] Show context menu when right clicking storage item(rename, unlink, create folder)
- [x] New folder button
- [ ] New storage button
- [x] Show note count of folder
- [ ] Tag List
## Note List
- [ ] Show progress of Tasks in Markdown note
- [ ] Drag & Drop Note #73
- [ ] Multiple notes manuplation #94
  - [ ] Delete
  - [ ] Move to other storage/folder
  - [ ] Change Tag
- [x] Sort notes
## Snippet Note
- [ ] Configurable syntax list
  - [ ] Syntax specific indent settings
  - [ ] Set/unset active syntax modes(Hide inactive modes from context menu by default) #68
- [ ] Resizable layout #81
- [ ] Re-arrange the order of sub-notes #190 
## Editor
- [x] Replace Ace editor with Codemirror -- v0.7.0
  - [x] Fix wrong syntax highlighting of codeblock #40 
  - [x] Wrong behavior when typing chracters with Spanish accent #54
- [ ] Scroll past the bottom most line of the editor #94
- [ ] Tag autocomplete #192 
### Markdown Editor
- [ ] Preview option #116
  - [ ] 2-pane
  - [ ] Preview mode
  - [ ] Distraction free mode
- [ ] Remove last list item when `Enter` pressed on empty list item. #42
- [ ] Task list should append `- [ ]` instead of `-` when `Enter` pressed.
- [ ] Depth control of List (Tab->deeper / Untab->shallower) #53
- [ ] Spell checking #76
- [ ] Image supporting #80
- [ ] Note link(Navigation between notes by a link) #41
- [x] Diagrams #134
  - [x] Flow chart
  - [x] Sequence
- [ ] Word count #94
- [ ] Toolbar #94
- [ ] Print #133
- [ ] Export #133 #52 
  - [ ] as a PDF
  - [ ] as a HTML
  - [ ] as a Markdown file
# Security
- [ ] Encrypted storage
# Integrations
## Cloud storage
- [ ] Google drive
- [ ] Dropbox
- [ ] Onedrive
- [ ] iCloud
- [ ] S3
- [ ] Gist as a Storage #74
- [ ] Git remote repository(Github, GitLab, Bitbucket)
## Snippet sharing
- [ ] Share snippet via Gist #48 #74
- [ ] Share snippet via Boostnote official site
  - [ ] Expiration option
## Other intergrations
- [ ] Github issue tracker

**Comment by dojineko** [comment]
:eyes:

**Comment by Rokt33r** [comment]
@dojineko ここは大丈夫です！来週水曜日が最後の試験で、その後からは夏休み開始ですw

**Comment by dojineko** [comment]
oh なんと 承知しましたーw

**Comment by robertweber95** [comment]
Would you mind if I helped with a couple of these features?

**Comment by Rokt33r** [comment]
@robertweber95 Thx for saying. But some features are confirmed to change :)
But, you can help me give some feedback. It makes me easy to decide how to improve the UX of this app. :)

**Comment by robertweber95** [comment]
Okay, will do! I would also love to contribute by developing too, so I will look out for other issues in the future.

**Comment by brpaz** [comment]
Nice list :)
For me I think to have the tags list in the sidebar with the possibility to filter is the most important.
Together with gist integration and "Finder/ menubar" improvements.

After that I think can finally start using Boostnote fulltime as my primary note/ snippets app.

**Comment by sami3d** [comment]
Just wondering -- is there any option to go back to the previous version?? With dark theme and etc ?? I used to use this app on day to day basis from note taking to do literally everything!! I had my personal setup and now after the update all messed up ... can't cope with the transition ... its been 10/15 days I couldn't even open the app .... It might sound silly but the transition wasn't smooth ... please help ..... thanks

**Comment by Rokt33r** [comment]
@sami3d Did you fail to migrate the notes of previous version?

**Comment by sami3d** [comment]
yeah .. i was able to migrate the notes .... its just the UI thats not being so friendly ... at least give back the dark theme for now ... thanks for your response though ...

**Comment by Rokt33r** [comment]
@sami3d 
Hang on a little more. I'll publish the new version tomorrow.
Dark theme and customisation of UI colors will be available after updating.

**Comment by Rokt33r** [comment]
@dojineko Could you join our slack? If it is possible, send a mail to me and I'll invite you. fluke8259@gmail.com

**Comment by dojineko** [comment]
@Rokt33r 

thx a lot! :smile: 
send mail to ur address. plz check it out.

**Comment by sami3d** [comment]
@Rokt33r thanks buddy... great job ...

**Comment by Rokt33r** [comment]
@sami3d You're welcome.
Ask me anytime. Your feedback nourishes our project.

**Comment by kazup01** [comment]
Thanks for everybody supports!
We made the new todolist. https://goo.gl/Mdu44q
From now on, we will update new one.
