### ISSUE TITLE
v0.6.3 will be released 8/14(CONFIRMED)

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#72]
Darktheme is finished. I'm preparing installer now.

---

Dark theme (70%)

![screen shot 2016-08-14 at 4 15 09 pm](https://cloud.githubusercontent.com/assets/5865853/17647749/5f79a2e6-623a-11e6-9953-f4ea2f5ed0fd.png)

---

#57 is fixed. v0.6.3 will be released Today. - Updated 2016/08/14 04:17AM GMT+9

---

I finished Finder. But, I have to check it works on other OS(Winodws, Ubuntu, Arch).
Hang on a little more. I'm sure I can release it this Sunday. - Updated 2016/08/13 21:27PM GMT+9

<img width="1144" alt="screen shot 2016-08-13 at 9 23 19 pm" src="https://cloud.githubusercontent.com/assets/5865853/17643166/2e338d80-619c-11e6-8a22-1a9ae4f41433.png">

---

I'm sorry for being late. This is the current status of F016/08/14 04:17AM GMT+9
---

I finished Finder. But, I have to check it works on other OS(Winodws, Ubuntu, Arch).
Hang on a little more. I'm sure I can release it this Sunday. - Updated 2016/08/13 21:27PM GMT+9

<img width="1144" alt="screen shot 2016-08-13 at 9 23 19 pm" src="https://cloud.githubusercontent.com/assets/5865853/17643166/2e338d80-619c-11e6-8a22-1a9ae4f41433.png">

---

I'm sorry for being late. This is the current status of Finder. - Updated 2016/08/13 13:~PM GMT+9

<img width="955" alt="screen shot 2016-08-13 at 2 09 22 pm" src="https://cloud.githubusercontent.com/assets/5865853/17641544/a0ac4826-615f-11e6-8deb-afcf184c9e57.png">

## Featuresinder. - Updated 2016/08/13 13:~PM GMT+9

<img width="955" alt="screen shot 2016-08-13 at 2 09 22 pm" src="https://cloud.githubusercontent.com/assets/5865853/17641544/a0ac4826-615f-11e6-8deb-afcf184c9e57.png">

## Features

- [x] Fix error when closing main window on Ubuntu #57
- [x] Finder
- [x] Dark theme (UI customization will be embeded the next update)
- [x] Folder color picker by @dotcs #77 
- [x] Fix layout bug #69 
- [x] expand/folder sidebar
- [x] Markdown snippet in Snippet note can be rendered just like Markdown note.
- ...and there might be more(check #68 for more information)

Sorry for being late, I wanted to finish it before August. But I couldn't.
Now, I have to deal with my semester tests which end on Wednesday. So, the my working will be continued after then.

**Comment by Rokt33r** [comment]
Sorry for delaying.. I have to postpone update on this Friday(20106/08/12).

**Comment by Rokt33r** [comment]
Released.
