### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Rokt33r** [BoostIO/Boostnote#86]
We will release an official version of Boostnote to Mac app store and Windows store before the winter is over. The app will be priced about $10.

But, you don't have to be worry if you are reading this issue from *Github*.
The app downloading from *Github* will remain **FREE**. And we will keep provide updates as we've done.

There are 2 reasons.

- To expose our app to more people.
- To provide more stable and safe build.

---

If you want to contribute, please join our slack. I'll send a invitation if you send to me a mail. fluke8259@gmail.com
Contributing is not only writing code. We are badly want to know what makes improve your work.
So, If you have some features you want, please feel free to tell us.

# Roadmap
- Markdown note
  - [ ] Image insertion #80 
- [ ] Web app
- [ ] Mobile app #55 
- [ ] CLI app
- Cloud Storage Integrations
  - [ ] Dropbox
  - [ ] Google Drive
  - [ ] One Drive
  - [ ] Box 
  - [ ] iCloud
- Task Reminder Integrations
  - [ ] WunderList
  - [ ] iCloud reminder
- Messenger Integrations
  - [ ] Share a note thru Public URL and send it to messenger
    - [ ] Facebook Messenger
    - [ ] Slack
    - [ ] ...
- Github Integrations
  - [ ] Issue tracker management #67 
  - [ ] Gist as a storage #74 
  - [ ] Github repository as a storage
- Development
  - [ ] CI (It is very painful to packging app for multiple OSs)
  - [ ] Test suite
    - [x] data api
  - [ ] Documentation

**Comment by brpaz** [comment]
Regarding CI, you could use [Travis](http://travis-ci.org) to package the app, when a new push when a new tag is created and to upload the build result to some place.

Edit: It looks like its compatible with GitHub Releases (https://docs.travis-ci.com/user/deployment/releases)

I might be able to help you with that.

**Comment by darahak** [comment]
It would be great to have instructions on the `readme.md` for build, test, and install.
With all the tooling nowadays, I'm afraid I might do something wrong.

**Comment by Rokt33r** [comment]
@darahak 
Sorry, I didn't notice the document had been removed. Check the below link.
https://github.com/BoostIO/Boostnote/blob/master/docs/build.md

**Comment by darahak** [comment]
And you also updated the readme. Thanks! :+1:

**Comment by Rokt33r** [comment]
Closed. These items will be maintained from #2
